name: ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: gradle
          args: |
            test
            build
